execution_env=local
#execution_env=remote


demoUrl=https://demo-gcd.omnna.live/index.php
ssUrl=https://ss-gcd.omnna.live/index.phphttps://demo-gcd.omnna.live/index.php
username=admin
password=!G0lF#2025xY7$
#password=test@12345
searchProductName=iPhone